[package]
name = "path-matcher"
version = "0.1.0"
authors = ["m77can <m77can@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "path_matcher"

[dependencies]
regex = "1.5.4"
